# For more information: https://laravel.com/docs/sail
version: '3'
services:
    writemv:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        labels:
            - traefik.enable=true
            - traefik.docker.network=docker
            - traefik.http.routers.writemv.entrypoints=http,https
            - traefik.http.routers.writemv.rule=Host(`writemv.this.lan`) # You can use any domain allowed by your TLS certificate
            - traefik.http.routers.writemv.tls=true
            - traefik.http.routers.writemv.service=writemv@docker
            - traefik.http.services.writemv.loadbalancer.server.port=80 # Adapt to the exposed port in the service
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - docker
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - docker
            - sail
            
networks:
    sail:
       driver: bridge
    docker:
       external: true
            
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
