# For more information: https://laravel.com/docs/sail
version: '3'
services:
    writemv:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - docker
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - docker
            - sail
            
networks:
    sail:
       driver: bridge
    docker:
       external: true
            
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
